package com.homestayManagement.homestayManagement.dto.response;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;

public record AdminBookingDetailResponse(
        Long bookingId,
        String bookingCode,
        Long bookingDetailId,
        LocalDateTime bookingDate,
        String bookingStatus,
        String detailStatus,
        Long roomId,
        String roomNumber,
        String roomTypeName,
        LocalDateTime checkInTarget,
        LocalDateTime checkOutTarget,
        Integer numberOfAdults,
        Integer numberOfChildren,
        BigDecimal priceAtBooking,
        BigDecimal allocatedDiscount,
        BigDecimal finalRoomAmount,
        String voucherCode,
        String voucherDiscountType,
        BigDecimal voucherDiscountValue,
        BigDecimal roomChargeBeforeDiscount,
        BigDecimal roomDiscountAmount,
        boolean customerConfirmed,
        String customerFeedback,
        LocalDateTime customerFeedbackAt,
        String rentType,
        AdminBookingCustomerResponse customer,
        List<AdminCustomerHistoryGuestResponse> guests,
        List<AdminBookingCheckInResponse> checkInRecords,
        boolean housekeepingInspectionCompleted,
        List<AdminInvoiceServiceItemResponse> serviceItems,
        List<AdminInvoicePenaltyItemResponse> penaltyItems,
        List<RoomIncidentResponse> incidents,
        AdminBookingInvoiceSummaryResponse invoice,
        java.math.BigDecimal paidAmount,
        List<AdminPaymentResponse> payments,
        List<FacilityServiceResponse> facilityServices,
        List<InventoryServiceResponse> inventoryServices,
        List<RoomMiniBarItemResponse> miniBarItems,
        List<RulesPenaltyResponse> penaltyRules,
        Integer extensionHours,
        BigDecimal extensionAmount,
        String cancellationReason,
        LocalDateTime cancelledAt,
        Integer refundRate,
        BigDecimal refundAmount,
        String refundStatus,
        String refundInfo,
        LocalDateTime refundCompletedAt,
        String refundHandledBy
) {
    public AdminBookingDetailResponse(
            Long bookingId,
            String bookingCode,
            Long bookingDetailId,
            LocalDateTime bookingDate,
            String bookingStatus,
            String detailStatus,
            Long roomId,
            String roomNumber,
            String roomTypeName,
            LocalDateTime checkInTarget,
            LocalDateTime checkOutTarget,
            Integer numberOfAdults,
            Integer numberOfChildren,
            BigDecimal priceAtBooking,
            BigDecimal allocatedDiscount,
            BigDecimal finalRoomAmount,
            String voucherCode,
            String voucherDiscountType,
            BigDecimal voucherDiscountValue,
            BigDecimal roomChargeBeforeDiscount,
            BigDecimal roomDiscountAmount,
            boolean customerConfirmed,
            String customerFeedback,
            LocalDateTime customerFeedbackAt,
            String rentType,
            AdminBookingCustomerResponse customer,
            List<AdminCustomerHistoryGuestResponse> guests,
            List<AdminBookingCheckInResponse> checkInRecords,
            boolean housekeepingInspectionCompleted,
            List<AdminInvoiceServiceItemResponse> serviceItems,
            List<AdminInvoicePenaltyItemResponse> penaltyItems,
            AdminBookingInvoiceSummaryResponse invoice,
            java.math.BigDecimal paidAmount,
            List<AdminPaymentResponse> payments,
            List<FacilityServiceResponse> facilityServices,
            List<InventoryServiceResponse> inventoryServices,
            List<RoomMiniBarItemResponse> miniBarItems,
            List<RulesPenaltyResponse> penaltyRules,
            Integer extensionHours,
            BigDecimal extensionAmount,
            String cancellationReason,
            LocalDateTime cancelledAt,
            Integer refundRate,
            BigDecimal refundAmount,
            String refundStatus,
            String refundInfo,
            LocalDateTime refundCompletedAt,
            String refundHandledBy
    ) {
        this(
                bookingId, bookingCode, bookingDetailId, bookingDate, bookingStatus, detailStatus,
                roomId, roomNumber, roomTypeName, checkInTarget, checkOutTarget,
                numberOfAdults, numberOfChildren, priceAtBooking, allocatedDiscount, finalRoomAmount,
                voucherCode, voucherDiscountType, voucherDiscountValue, roomChargeBeforeDiscount,
                roomDiscountAmount, customerConfirmed, customerFeedback, customerFeedbackAt,
                rentType, customer, guests, checkInRecords, housekeepingInspectionCompleted,
                serviceItems, penaltyItems, List.of(), invoice, paidAmount, payments,
                facilityServices, inventoryServices, miniBarItems, penaltyRules,
                extensionHours, extensionAmount, cancellationReason, cancelledAt,
                refundRate, refundAmount, refundStatus, refundInfo, refundCompletedAt, refundHandledBy
        );
    }
}
